### PR TITLE
[FIX] All required changes to make Planetary compile and run in xcode 11

### PR DESCRIPTION
**Pull request by kemalenver**
You can open this in xcode 11 and it should work out of the box by building and running on a device (simulator wont work as it requires apple music subscription with some albums added to your collection)

Submodules are still enabled in the repo (I should remove them) but I copied in the source instead to make it easier to change and get working.

General updates include:
Update for 64bit architecture
Updates to project file and build settings
Update to make work with default clang compiler
Update to a compatible cinder with some tweaks
Update boost
(cinder/boost combination is a bit frankenstein)
Rotation lock to landscape to avoid deprecated setStatusBar code
Touch fixes
General things to stop crashes (including some threading :/)
Some hacks and fixes to make iPhone compile and build and look 'ok'

Rendering/textures etc is the original bloom version.  opengl is still deprecated on apple platforms, but since this code uses glow effects, on modern devices there is no need for any fancy stuff and it hums along quite nicely.  Even though it can run on iOS 9 devices+ I recomend running on as new hardware as possible as some optimisations (loading) was removed to facilitate getting it to work.

### CODE REVIEW

**Comment by kemalenver** [comment]
Sorry it's so huge - I wasn't intending to make a PR for this when I started because I didn't think I'd get it working!  All the submodules and bits and pieces are now part of the project rather than submodules.  It was more convenient for me to work that way when I was fiddling around.

**Comment by jwalthew** [comment]
@straup and @RandomEtc the team from Cooper Hewitt will be in touch with you soon!

**Comment by finoradin** [comment]
Considering the `diff` is useless, I'm curious what the benchmark or best practice for review is here @RandomEtc @straup? Get a dev environment verified working / building on the museum's end?

**Comment by straup** [comment]
@finoradin Ultimately the decision should rest with @jwalthew and the museum but I would suggest the rule of thumb going forward should be "use submodules", or the functional equivalent.

I say that for two reasons:

1. It makes the diff/review process manageable, or at least "more manageable".
2. It removes any ambiguity about what the museum has collected, for example "not Cinder".

**Comment by jwalthew** [comment]
@finoradin Hmm. Was going to make the exact opposite argument, and say that merging submodules into the [fix] source code seems like it's probably a good idea--i.e better for the long-term preservation of the function of the code, since it reduces the number of external links we rely on.  What do you think? Bloom's GitHub is still there for the submodules to link to, but probably not forever.  What happens if someone were to update the submodules- would it force updates in the Planetary code (asking does it link at a particular commit or merge to latest state)?

**Comment by straup** [comment]
@jwalthew One approach would be to fork [1] all of the dependencies in the Cooper Hewitt's own GitHub account and to list those dependencies as sub-modules, rather than the original sources.

[1] https://guides.github.com/activities/forking/

**Comment by kemalenver** [comment]
It's probably a good idea to fork the submodules to keep everything organised and easier to diff.  It will add an overhead though in the future if anyone wants to make more fixes/improvements, as PRs will need to be raised to all the relevant repos. 🤷‍♂️

**Comment by kemalenver** [comment]
Another alternative is to just leave this as is and merge it to another branch?

**Comment by straup** [comment]
It sounds as though another branch with submodules would be the fastest way for people to review the changes. Once that is done the museum can decide whether or not they want to fork/host their own copies of the dependencies which could then use be use to update the Planetary submodules pointers.

**Comment by RandomEtc** [comment]
Hey folks - I have some time in the upcoming long weekend and I'm happy to try to tease this apart as a volunteer. I have a couple of unanswered emails from CH folks so I'll get to those first 😜 

I think our goals are (a) get something that someone could check out and build with modern XCode (b) make a readable diff so that people can follow the evolution of the project (c) ideally keep clean lines between what's Planetary and what's Cinder, Boost and other dependencies.

I applaud Kamal for getting to (a) and we could merge as-is and meet that I think (I'll start by confirming that). 

I do think (b) is important enough to sink a little bit of time into. If we wait another 8 years for someone to pick this up and play with it again, there's a risk if we just pile all the dependencies into this repo that it would be impossible to follow!

I prefer submodules to satisfy (c), but I do think it's possible we could "vendor" the dependencies in as separate commits and then apply Kamal's patches that allowed Planetary to build, and that ultimately it might be better for everyone if this repo was self-contained.

As I noted in Twitter, I admire Kamal for not letting perfect be the enemy of good enough, and for actually getting the thing working! (I tried, but only in a VM, I never got it working in new XCodes!). I'll try to contribute a few hours of gardening in the same spirit 😬

**Comment by jwalthew** [comment]
We're happy to have @kemalenver and @RandomEtc sort out the best way to fork and branch as needed to make the review easiest-- whatever seems most logical and useful from a development perspective. Our role in conservation (working with @finoradin) will be to document the changes and make sure that they are captured in the collections records.  Let us know what you need us to do to facilitate review, if anything. Afterward, we'd like to set up technical interviews with each of you so that we can document this iteration. (The term "iteration" has a specific meaning in the conservation of time-based-media and performance art-- an "iteration report" contains descriptions of what changes occurred in subsequent iterations and who was responsible for decision-making. We use a template designed by the Guggenheim's former conservator of tbm Joanna Phillips that has been adapted for our institution).

**Comment by kemalenver** [comment]
@RandomEtc Sounds good Tom thanks for picking up the fun bit :p.  If I'd known I was going to get it working and contribute back I'd have probably made some effort to make this easier.  If you need any help with that let me know.

**Comment by jwalthew** [comment]
@kemalenver Made a new branch (as you suggested above) to merge your work to: planetary_remastered. Then we're forking it over to a separate CooperHewittCollection organization which will host collections objects separately from other code.

**Comment by kemalenver** [comment]
Okay no problem - I'll make sure the stuff I have here compiles easily and is ready to go before merging to your new branch.

**Comment by kemalenver** [comment]
Hi @jwalthew  - I just pushed a change to this branch and confirmed that it can be checked out and built on a device in Xcode 12.  I also updated the README to include some instructions about how to get it working and its limitations.  I'll open a new PR now to the planetary_remastered branch.

**Pull request closed without merging**
